### ISSUE TITLE
FOIA menu bar

### ISSUE THREAD

**Issue by yowill** [18F/pclob#78]
The FOIA menu bar on the top of the homepage needs to be removed. We have decided to just keep it at the bottom right of the page, where it is also currently located (ie, leave that one there.

**Comment by toolness** [comment]
Ok, I've fixed this, but I wanted to also note that the FOIA link in the menu bar used to be under the "Reports" section of the menu bar, which makes sense since "FOIA Reports" comprises most of that section.  So it might make sense to move it back under "Reports" rather than removing it entirely from the top navbar.

In any case, though, for now I've followed this issue literally and just removed it entirely from the nav bar. We can open a separate issue if we decide to bring it back in under the "Reports" section if we want.
