### ISSUE TITLE
Events & Press issues

### ISSUE THREAD

**Issue by yowill** [18F/pclob#79]
- [x] ~~Add the following, June 27, 2017—“Board Member Elisebeth Collins’ Testimony before the Senate Judiciary Committee for a Hearing Titled, “ The FISA Amendments Act: Reauthorizing America’s Vital National Security Authority and Protecting Privacy and Civil Liberties.”  Include the attached link of her testimony.~~ Spun out into #88.

~~[Uploading SJC Collins Testimony 6-27-17 final.pdf…]()~~

- [x] ~~Add the May 10, 2016 “Board Member Rachel Brand Testimony Before the Senate Judiciary Committee…” from the current “Newsroom” website section.~~ This seems to already be fixed.

- [x] ~~On the March 29, 2016 release “Chairman David Medine to Resign….,” the header is currently all caps, but should not be.~~ Spun out into #89.

**Comment by toolness** [comment]
@yowill somehow that PDF attachment didn't work--the link just points to this issue. Can you re-upload it, or email it to me?

**Comment by toolness** [comment]
Regarding the second item, that does seem to already be listed in the Events & Press section of the new site:

https://federalist-proxy.app.cloud.gov/site/18f/pclob/newsroom/2016/05/10/board-member-rachel-brand-testimony-before-the-senate-judicary-hearing.html

Did the PCLOB folks want something different?  Or was that not appearing earlier for some reason?

Finally, I think the third checkbox is a great candidate for training, since it's a very easy-to-fix bug.

**Comment by toolness** [comment]
Ok, I've spun out the remaining two issues to #88 and #89 and will close this one.
